spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    drvier-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true