spring:
  jpa:
    #    defer-datasource-initialization: true # 애플리케이션 실행시 파일 설정 data.sql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    drvier-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true